### ISSUE TITLE
about add path in readme

### ISSUE THREAD

**Issue by Oxygenxy** [CTU-IIG/TORSCHE2017#2]
![8b2511c1-36bc-4114-9c6d-9bbcef584372](https://user-images.githubusercontent.com/17754289/36147762-654ed926-10b1-11e8-8e17-0bb5488dc026.png)
There is no stdemos folder in toolbox,so should we copy stemos in +torsche to toolbox?

**Comment by dvoraj57** [comment]
Hi, 
Thank you for your reported issue. I have improved the README.md file according to the folder structure of TORSCHE2017.

Jan
